### ISSUE TITLE
Why Express.js?

### ISSUE THREAD

**Issue by aneesh-neelam** [ayushagarwal95/VIT-Faculty-Database#1]
Why are you using Express.js? You don't need a web framework for this. 

Just a script would do, right? Just scrape and dump in MongoDB. One time execution.

**Comment by kishore-narendran** [comment]
Redundant much?
Modify this.
https://github.com/kishore-narendran/FacultyInformationScraper

**Comment by aneesh-neelam** [comment]
What ma? Where is `requirements.txt`. Also, where is `CaptchaParser.py`? Do I have to pull that from @karthikb351's repository?

**Comment by kishore-narendran** [comment]
I didn't follow Python design principles and all. Just use straight.
Yeah, pull and use. I made that repo before I knew how to write markdown and proper documentation

**Comment by aneesh-neelam** [comment]
That's not a design principle. It's a Python project requirement, especially if you have used external dependencies using `pip`. It's just like how every Node.js/io.js project has a `package.json`. `README.md` and `LICENSE` are GitHub's recommendations. 

I cannot use without knowing what dependencies are needed. The minimum files you need for every Python project are `requirements.txt` and `runtime.txt`. Check [this](https://github.com/aneesh-neelam/Portfolio) out for more information. 

What you added to that repository was just one Python file out of a larger project. Will need to manually go through the code to find which dependencies, and I still wouldn't know if the latest versions would do or if I need specific ones. 

You made this repository 4 months ago. That isn't too long ago.

**Comment by aneesh-neelam** [comment]
Please use `pip` rather than `easy_install`. `pip` takes care of a package's dependencies, whereas `easy_install` doesn't.

**Comment by ayushagarwal95** [comment]
I made this on my own for my own learning experience. I understand node a lot better now that I have worked on this completely by myself.
